### ISSUE TITLE
Application shuts off after 3 min

### ISSUE THREAD

**Issue by GeorgePontos** [cy8018/RadioPlayer.Android#1]
I have android 10 and the app closes after 3 min when the screen turns off.

android.permission.FOREGROUND_SERVICE must be used to play music/radio in background when screen turns off.

**Comment by MonkeyMok** [comment]
Audio Stream WIthout FOREGROUND? How they user can listen song.. He mus add FOREGROUND

**Comment by cy8018** [comment]
FOREGROUND_SERVICE added, please have a try.
